# Python Machine Learning
- Created by DaBloat
- Based in my learnings in "Python Machine Learning" by Wei-Meng Lee

## Chapter 1: Problem types solved by ML

### Classification
- "IDENTIFYING"

### Regression
- "FORECASTING"

### Clustering
- "Grouping into natural clumps"

## Types of ML Algorithms
### Supervised Learning
- using Labeled dataset

### Unsupervised Learning
- using unlabeled dataset

## Chapter 2: Numpy Array
- Python List is computationally expensive
- arrays are type of ndarrays  (n-dimeansional array) that all elements are same
### Numpy Use

In [2]:
# setting the alias np to numpy seems to be a custom!
import numpy as np

In [3]:
# creating numpy arrays naturaly
sample = np.arange(5) # Creates array from 0 - 4
print(sample)

[0 1 2 3 4]


In [4]:
print(sample.shape) # works like as len() for matrices, originaly returns a tuple

(5,)


In [5]:
skips = np.arange(1, 10, 2) # (starting element, # of elements, Skips)
print(skips)

[1 3 5 7 9]


In [6]:
zero = np.zeros(5) # Creates a zero array
print(zero)

[0. 0. 0. 0. 0.]


In [7]:
matrix = np.zeros((5,3)) # for matrices size (or shape in this matter), it accepts tuples (row,col) 
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
print(matrix.shape) # also shown in the shape (row,col)

(5, 3)


In [9]:
repeat = np.full((3,5),1) # (Matrix sizze in tuple, integer to be repeated)
print(repeat)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
identity = np.eye(5) # Creates an Identity Matrix, (size of the identity matrix)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
randm = np.random.random((4,4)) # random module (size in tuple)
print(randm)

[[0.31260265 0.15374039 0.51515758 0.65419097]
 [0.44374793 0.66256886 0.63498548 0.95660441]
 [0.27151956 0.67064542 0.72484002 0.36262636]
 [0.67984607 0.16249886 0.56771594 0.23385191]]


In [12]:
listings = [1,2,3,4,5] # Or you can use list to feed as an array
lits = np.array(listings)
print(lits)

[1 2 3 4 5]


### Numpy Indexing

In [13]:
# you can do a variety of ways to do indexing in numpy arrays!
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]
number = np.array([l1,l2]) # you can do this in creating matrices

print(number)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [14]:
# you can use classic indexing
print(number[0][0]) # The first row and first column element

1


In [15]:
# or just throw the row x col position seperated by as comma
print(number[1,4]) # The last value in the matrix

0


In [16]:
# you can also throw a list for indexing
print(number[[0],[2,4]]) # (row, selected column index in the list)

[3 5]


In [17]:
# another exmaple
s = np.array(l1) 
print(s[[1,4]]) # returns a list of the index

[2 5]


In [18]:
# You can also do "Boolean Indexing"
print(number>2) # Returns true when the element is greater than 2

[[False False  True  True  True]
 [ True  True  True  True False]]


In [19]:
# This is good for extaracting values/data/elements that returns true in your condition
print(number[number>2]) # This returns the values that are less than 2

[3 4 5 6 7 8 9]


In [20]:
odd = number[number % 2 == 1] # return odd integer values
print(odd)

[1 3 5 7 9]


### Numpy Array Slicing

In [21]:
# same concept in string slicing
yna = "I Love your smile"
yna[0:10] # [start:stop]  index

'I Love you'

In [22]:
# or using negative index
yna[:-7]

'I Love you'

In [23]:
yna[-5:] # you get the point
# just the concept of [start:stop]

'smile'

In [24]:
# using numpy
number3 = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15]
    ]
)
print(number3) # 3x5 matrix
print(number3.shape) # confirmed by this attrib.

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


In [25]:
print(number3[1:3])
# starts @ index 1 and stops @ index 3 (which it will not include the index 3)
# additionaly its the same as number3[1:]

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [26]:
print(number3[1: , :3])
# this time each row is sliced again by column according to
# start:stop

[[ 6  7  8]
 [11 12 13]]


In [27]:
# using negative index
print(number3[-2:, :-2])

[[ 6  7  8]
 [11 12 13]]


In [28]:
print(number3[2:,:].shape) # gets the shape of the 2nd Row (should be 1,5)

(1, 5)


### Array Reshaping

In [29]:
number3.shape # return the tuple of shape/size of the matrix (row, col)

(3, 5)

In [30]:
number3.reshape(5,3) # reshape the matrix from left to right

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [31]:
number3.flatten() # Return a copy of the array collapsed into one dimension.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
number3.ravel() # Return a contiguous flattened array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Array Maths

In [33]:
x1 = np.array([[1,2,3],[4,5,6]])
y1 = np.array([[6,5,4],[3,2,1]])

In [34]:
print(x1)

[[1 2 3]
 [4 5 6]]


In [35]:
print(y1)

[[6 5 4]
 [3 2 1]]


In [36]:
# You can do 4 basic operations

add = x1 + y1 # It adds the matrix element by element
print(add) # ex. x1[0,1] + y1[0,1]

[[7 7 7]
 [7 7 7]]


In [37]:
sub = x1 - y1 # It subtracts the matrix element by element
print(sub)

[[-5 -3 -1]
 [ 1  3  5]]


In [38]:
mul = x1 * y1 # It multiplies the matrix element by element
print(mul)

[[ 6 10 12]
 [12 10  6]]


In [39]:
div = x1 / y1 # It divide the matrix element by element
print(div)

[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


In [40]:
# add other operations
# modulo %
# exponent **
# to name a few
# always in a element by element basis
# given the shape is the same between the two
x2 = np.array([[1,2,3],[4,5,6],[1,23,45]])
# x3 = x1 + x2 : could result to an error

In [41]:
# EXAMPLE FROM THE BOOK #
names = np.array(['Ann','Joe','Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

# Now say that you want to calculate the Body Mass Index (BMI) of this group
# of people. The formula to calculate BMI is as follows:
# ■ Divide the weight in kilograms (kg) by the height in meters (m)
# ■ Divide the answer by the height again
# Using the BMI, you can classify a person as healthy, overweight, or under-
# weight using the following categories:
#  Underweight if BMI < 18.5
#  Overweight if BMI > 25
# ■ Normal weight if 18.5 <= BMI <= 25

In [42]:
bmi = weights/heights **2
print(bmi)

[28.88888889 14.51836889 23.046875  ]


In [43]:
print("Overweight: " , names[bmi>25]) # See the use of boolean indexing and division

Overweight:  ['Ann']


In [44]:
print("Underweight: " , names[bmi<18.5])

Underweight:  ['Joe']


In [45]:
print("Healthy: " , names[(bmi>=18.5) & (bmi<=25)]) 
# Logical operators in boolean indexing
# these operator will work when you enclosed your statesment inside a parenthesis
# array[(statement1) logical operator (statement2)]

Healthy:  ['Mark']


### Dot Product

In [46]:
# achieved by multiplying row values to column values and its summation
f1 = np.array([[1,2,3],[4,5,6]])
f2 = np.array([[7,8],[9,10],[11,12]])
xdot = np.dot(f1,f2)

"""
1 2 3    dotproduct     7  8
4 5 6                   9  10
                        11 12
answer = * *
         * *
answer[0,0] = 1*7 + 2*9 + 3*11 = 58
answer[0,1] = 1*8 + 2*10 + 3*12 = 64

and so on...
"""  
print(xdot)

[[ 58  64]
 [139 154]]


### Matrix

In [47]:
# matrix are stricly 2 dimensional
# Created same as the numpy arrays
x2 = np.matrix([[1,2,3],[4,5,5]])
print(x2)

[[1 2 3]
 [4 5 5]]


In [48]:
print(type(x1))
# you can convert numpy array to matrix using
x1 = np.asmatrix(x1)
print(type(x1))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [49]:
# matrix vs array in multiplication
# when you multiply numpy arrays, they do element by element multiplication
# but when you multiply matrices, they do dot product

try1 = np.array([[1,2],[3,4]])
try2 = np.array([[5,6],[7,8]])

mul = try1 * try2 # Element by element multiplication
print(mul)

[[ 5 12]
 [21 32]]


In [50]:
try1 = np.asmatrix(try1)
try2 = np.asmatrix(try2)

mmul = try1*try2 # Scalar/Dot Product ; like np.dot()
print(mmul)

[[19 22]
 [43 50]]


### Cumulative Sum

In [51]:
x1 = np.asarray(x1) # it is set to be a matrix in past blocks (converted back to array)
print(x1.cumsum()) # used to display the total sum of data as it grows with time (cumulative sum)
# cumsum hehe

[ 1  3  6 10 15 21]


In [52]:
# you can modify its direction by the axis parameter

print(x1.cumsum(axis=0)) # Get the cumulative sum by columns

[[1 2 3]
 [5 7 9]]


In [53]:
print(x1.cumsum(axis=1)) # Get the Cumulative sum by rows

[[ 1  3  6]
 [ 4  9 15]]


### Numpy sorting

In [54]:
# np.sort() doesn't modify the original array

minors = np.array([16,14,12,17])
print(np.sort(minors))

[12 14 16 17]


In [55]:
print(minors) # it doesn't change

[16 14 12 17]


In [56]:
# .sort() after the numpy array will sort and modify it
minors.sort()
print(minors)

[12 14 16 17]


In [57]:
# .argsort() or np.argsort() will return the the indices 
# of the array and sort it base to the original value
drake_likes = np.array([16,14,12,17])
print(drake_likes.argsort())

[2 1 0 3]


In [58]:
drake_rank = np.argsort(drake_likes)
print(drake_likes[drake_rank]) # can be used like boolean index' manner 

[12 14 16 17]


### Numpy Array Assignments

In [59]:
# Copy by reference
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1)
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [60]:
a2 = a1 # Copying By reference
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [61]:
a1[0,0] = 11 # Making changes to the original array
print(a1)

[[11  2  3  4]
 [ 5  6  7  8]]


In [62]:
print(a2) # will reflect to the copy

[[11  2  3  4]
 [ 5  6  7  8]]


In [63]:
# even reshapes will reflect
a1.shape = 1,-1
print(a1)

[[11  2  3  4  5  6  7  8]]


In [64]:
print(a2)

[[11  2  3  4  5  6  7  8]]


In [65]:
a1 = np.array(list1) # revert back for next example

# Copy by View (Shallow copy)
a2 = a1.view() # copying using the view method
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [66]:
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [67]:
a1[0,0] = 11 # Value changes to the array 
print(a1)

[[11  2  3  4]
 [ 5  6  7  8]]


In [68]:
print(a2) # will reflect

[[11  2  3  4]
 [ 5  6  7  8]]


In [69]:
a1.shape = 1,-1 # but shaping
print(a1)

[[11  2  3  4  5  6  7  8]]


In [70]:
print(a2) # will not reflect

[[11  2  3  4]
 [ 5  6  7  8]]


In [71]:
a1 = np.array(list1) # revert back for next example

# Copying by Value (Deep Copy)
a2 = a1.copy() #Copy
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [72]:
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [73]:
a1[0,0] = 11 # Value changes to the array 
print(a1)

[[11  2  3  4]
 [ 5  6  7  8]]


In [74]:
print(a2) # will not reflect to the copy

[[1 2 3 4]
 [5 6 7 8]]


In [75]:
# as well as reshaping
a1.shape = 1,-1 # but shaping
print(a1)

[[11  2  3  4  5  6  7  8]]


In [76]:
print(a2) # CHAD

[[1 2 3 4]
 [5 6 7 8]]


## Chapter 3 Manipulating Tabular Data in Pandas

- Numpy is good in n-dimension array, not good for other data science stuff
- Real life data are mostly in tabular form
- Mostly this is in csv's
- Pandas are suitable for data that stored in tables
- good for relational or labeled data in easy and inuitive manner

### Pandas Series
- one dimensional numpy like array
- behave like a dictionary

In [77]:
import pandas as pd # use of pd as an alias for pandas is the custom so use it
series = pd.Series([1,2,3,4,5]) # as an on dimensional array, indexing will starts @ 0
print(series) # printing a series will return a 2 cols, 1 is its index other is his values

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [78]:
# setting index will CHANGE indexing to your preferrence
series = pd.Series([1,2,3,4,5], index=['a','b','c','d','c'])
print(series) # index not need to be a Unique value

a    1
b    2
c    3
d    4
c    5
dtype: int64


### Accessing Elements in a Series

In [79]:
print(series['a']) # same as accesing arrays

1


In [80]:
print(series[0]) # this works but its a deprecated function so always treat keys as it is

1


/tmp/ipykernel_202923/4205799841.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[0]) # this works but its a deprecated function so always treat keys as it is


In [81]:
print(series.loc['a']) # loc or location can do that too

1


In [82]:
print(series.loc['c']) # this display a Series that shows both have 'c'|

c    3
c    5
dtype: int64


In [83]:
 print(series[3:]) # You can still do this

d    4
c    5
dtype: int64


In [84]:
# or use Integer Location or iloc!
print(series.iloc[-1])

5


In [85]:
print(series.iloc[:-2]) # print start to the 3rd to the last!

a    1
b    2
c    3
dtype: int64


### Specifying a Datetime Range as the Index of a Series

In [86]:
dates = pd.date_range("20190525", periods=12) 
# Date range are used the have a running sequences of dates / "TIMESERIES"
# Without even manually typing them
print(dates) #returns a datetimeIndex Object where values are datetime

DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03', '2019-06-04', '2019-06-05'],
              dtype='datetime64[ns]', freq='D')


In [87]:
series = pd.Series(np.arange(1,13)) # creates Series with numpy array using np.arrange(start,stop,step)
series.index = dates # Series.index is an attributes that you can change the index
print(series)

2019-05-25     1
2019-05-26     2
2019-05-27     3
2019-05-28     4
2019-05-29     5
2019-05-30     6
2019-05-31     7
2019-06-01     8
2019-06-02     9
2019-06-03    10
2019-06-04    11
2019-06-05    12
Freq: D, dtype: int64


### Date Ranges

In [88]:
dates2 = pd.date_range("20240101", periods=12, freq="D")
# the String value is the starting date using date format year-month-day
# periods is the step of the timeseries
# freq or the frequency are the ranges or manner of how dates will be modified
# freq can be 'D' = daily (the default option), 'MS' = Monthly Start, 'ME' = Monthly End
# 'YS' = Year Start, 'YE' = Year End
print(dates2)

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12'],
              dtype='datetime64[ns]', freq='D')


In [89]:
dates2 = pd.date_range("20240101", periods=12, freq="MS") 
# Periods are added Monthly, but outputs are at the first day of the month
print(dates2)

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01'],
              dtype='datetime64[ns]', freq='MS')


In [90]:
dates2 = pd.date_range("20240101", periods=12, freq="ME")
# Periods are added Monthly, but outputs are at the last day of the month
print(dates2)

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31'],
              dtype='datetime64[ns]', freq='ME')


In [91]:
# example 01-05-2024
dates3 = pd.date_range("01-05-2024", periods=12) # in this matter im not really sure what the time format
# but it seems that pandas proccessed the dates as Month-Date-Year
print(dates3)

DatetimeIndex(['2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12',
               '2024-01-13', '2024-01-14', '2024-01-15', '2024-01-16'],
              dtype='datetime64[ns]', freq='D')


In [92]:
# example 01/05/2024
dates3 = pd.date_range("01/05/2024", periods=12, freq='MS') # seems it also applied to this way
# month-day-month
print(dates3)

DatetimeIndex(['2024-02-01', '2024-03-01', '2024-04-01', '2024-05-01',
               '2024-06-01', '2024-07-01', '2024-08-01', '2024-09-01',
               '2024-10-01', '2024-11-01', '2024-12-01', '2025-01-01'],
              dtype='datetime64[ns]', freq='MS')


In [93]:
# date_range can also handle time and freq can be 'h' which is the time is incremented
# Hourly for the period process
dates4 = pd.date_range("2019-05-17 12:00:00",periods=12, freq='h') # added a 24 hr-format time
print(dates4)

DatetimeIndex(['2019-05-17 12:00:00', '2019-05-17 13:00:00',
               '2019-05-17 14:00:00', '2019-05-17 15:00:00',
               '2019-05-17 16:00:00', '2019-05-17 17:00:00',
               '2019-05-17 18:00:00', '2019-05-17 19:00:00',
               '2019-05-17 20:00:00', '2019-05-17 21:00:00',
               '2019-05-17 22:00:00', '2019-05-17 23:00:00'],
              dtype='datetime64[ns]', freq='h')


### Pandas DataFrame

- Two Dimensional numpy like array
- mirrors the real life data
- can slice like a madman (both Series slicing and DataFrames Slicing)
- mostly this is extracting rows and columns are the job in pandas
- data manipulations and data cleaning is also involved
- Used for representation of data in Machine Learning

### Creating Data Frame

In [94]:
# pandas and are already imported to this notebook, please bear it in mind
df = pd.DataFrame(np.random.randn(10,4), # np.random.randn(rows,columns)
                  columns=list('ABCD')) # Changing the Column names to ABCD respectively
print(df)

          A         B         C         D
0  0.158294 -0.152097  0.962826  0.779027
1  0.571415 -0.791438  0.166042 -0.584373
2  0.157738  0.248846 -0.337934  1.557236
3 -1.968210 -0.833159 -0.642852  0.011324
4  0.658876 -1.296092 -2.520846 -0.901576
5  0.714369 -0.144770  0.431147 -1.430411
6 -0.354987 -1.719900 -1.002914  0.440027
7 -2.192925 -1.263645  1.371032  0.138926
8 -0.206288 -0.408219 -1.651362 -0.084739
9  1.265283  1.445400  0.875576 -0.502698


In [95]:
df.to_csv('data.csv', index=False) 
# Saving the dataframe to .csv without the annoying automatic index

In [96]:
# some of the datas you will work on is place to a .csv file, so you need to download it
# and read the csv file using pandas
df1 = pd.read_csv('data.csv')
print(df1)

          A         B         C         D
0  0.158294 -0.152097  0.962826  0.779027
1  0.571415 -0.791438  0.166042 -0.584373
2  0.157738  0.248846 -0.337934  1.557236
3 -1.968210 -0.833159 -0.642852  0.011324
4  0.658876 -1.296092 -2.520846 -0.901576
5  0.714369 -0.144770  0.431147 -1.430411
6 -0.354987 -1.719900 -1.002914  0.440027
7 -2.192925 -1.263645  1.371032  0.138926
8 -0.206288 -0.408219 -1.651362 -0.084739
9  1.265283  1.445400  0.875576 -0.502698


### Specifying the Index in a DataFrame

In [97]:
# Using the lesson we learn from date_range method
dates = pd.date_range('20240829', periods=10)
df1.index = dates
print(df1)

                   A         B         C         D
2024-08-29  0.158294 -0.152097  0.962826  0.779027
2024-08-30  0.571415 -0.791438  0.166042 -0.584373
2024-08-31  0.157738  0.248846 -0.337934  1.557236
2024-09-01 -1.968210 -0.833159 -0.642852  0.011324
2024-09-02  0.658876 -1.296092 -2.520846 -0.901576
2024-09-03  0.714369 -0.144770  0.431147 -1.430411
2024-09-04 -0.354987 -1.719900 -1.002914  0.440027
2024-09-05 -2.192925 -1.263645  1.371032  0.138926
2024-09-06 -0.206288 -0.408219 -1.651362 -0.084739
2024-09-07  1.265283  1.445400  0.875576 -0.502698


In [102]:
print(df1.index) # printing the modified indeces

DatetimeIndex(['2024-08-29', '2024-08-30', '2024-08-31', '2024-09-01',
               '2024-09-02', '2024-09-03', '2024-09-04', '2024-09-05',
               '2024-09-06', '2024-09-07'],
              dtype='datetime64[ns]', freq='D')


In [103]:
print(df1.values) # this just print solely the values without including indexes and column names

[[ 0.15829424 -0.15209698  0.9628257   0.7790274 ]
 [ 0.57141515 -0.79143833  0.16604205 -0.58437314]
 [ 0.15773772  0.24884627 -0.33793399  1.55723616]
 [-1.96820985 -0.83315908 -0.6428525   0.01132352]
 [ 0.65887608 -1.29609183 -2.52084636 -0.90157644]
 [ 0.71436937 -0.14477049  0.43114747 -1.43041131]
 [-0.35498677 -1.71989991 -1.00291382  0.44002746]
 [-2.19292523 -1.26364509  1.37103152  0.13892618]
 [-0.20628839 -0.40821865 -1.65136155 -0.08473901]
 [ 1.26528329  1.44539991  0.87557637 -0.5026983 ]]


### Generating Descriptive Statistics on the DataFrame

In [107]:
print(df1.describe()) 
# gives us descriptive analysis in data we are handling
# as of here we have
# count - number of data in the column
# mean - mean of the column
# min - minimum value in the column
# max - Maximum value  in the column
# variance (25% - 75%)

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.119643  -0.491507  -0.234929  -0.057726
std     1.136761   0.912949   1.240515   0.861000
min    -2.192925  -1.719900  -2.520846  -1.430411
25%    -0.317812  -1.156024  -0.912898  -0.563954
50%     0.158016  -0.599828  -0.085946  -0.036708
75%     0.637011  -0.146602   0.764469   0.364752
max     1.265283   1.445400   1.371032   1.557236


In [111]:
print(df1.mean()) # you can basically can compute the mean directly using .mean()

A   -0.119643
B   -0.491507
C   -0.234929
D   -0.057726
dtype: float64


In [113]:
print(df1.mean(1))
# parameter of mean (read the docs)
# but here .mean(0) is the default which get the mean by column
# while .mean(1) calculate the mean per row

2024-08-29    0.437013
2024-08-30   -0.159589
2024-08-31    0.406472
2024-09-01   -0.858224
2024-09-02   -1.014910
2024-09-03   -0.107416
2024-09-04   -0.659443
2024-09-05   -0.486653
2024-09-06   -0.587652
2024-09-07    0.770890
Freq: D, dtype: float64


### Extracting from DataFrames

In [119]:
df1.head() # gets the first five rows of the dataframe by default
# you can pass the number of you want to display in the parameter
# ex. df1.head(3) gives you first 3 rows of data 

A         B         C         D
2024-08-29  0.158294 -0.152097  0.962826  0.779027
2024-08-30  0.571415 -0.791438  0.166042 -0.584373
2024-08-31  0.157738  0.248846 -0.337934  1.557236
2024-09-01 -1.968210 -0.833159 -0.642852  0.011324
2024-09-02  0.658876 -1.296092 -2.520846 -0.901576

In [120]:
df1.head(3) # YEAH

A         B         C         D
2024-08-29  0.158294 -0.152097  0.962826  0.779027
2024-08-30  0.571415 -0.791438  0.166042 -0.584373
2024-08-31  0.157738  0.248846 -0.337934  1.557236

In [121]:
df1.tail() # This shows the last five rows of the dataframe by default
# also has same concept to the head

A         B         C         D
2024-09-03  0.714369 -0.144770  0.431147 -1.430411
2024-09-04 -0.354987 -1.719900 -1.002914  0.440027
2024-09-05 -2.192925 -1.263645  1.371032  0.138926
2024-09-06 -0.206288 -0.408219 -1.651362 -0.084739
2024-09-07  1.265283  1.445400  0.875576 -0.502698

### Selecting a Specific Column in a DataFrame

In [123]:
print(df1.A) # you can directly access a specific column as this
# that is why you should have a good naming conventions to your column names
# in this method, column names with spaces can't be accessible

2024-08-29    0.158294
2024-08-30    0.571415
2024-08-31    0.157738
2024-09-01   -1.968210
2024-09-02    0.658876
2024-09-03    0.714369
2024-09-04   -0.354987
2024-09-05   -2.192925
2024-09-06   -0.206288
2024-09-07    1.265283
Freq: D, Name: A, dtype: float64


In [125]:
# while you can also so this
print(df1["A"])
# which work even your column name has spaces, it works since you pass a string inside

2024-08-29    0.158294
2024-08-30    0.571415
2024-08-31    0.157738
2024-09-01   -1.968210
2024-09-02    0.658876
2024-09-03    0.714369
2024-09-04   -0.354987
2024-09-05   -2.192925
2024-09-06   -0.206288
2024-09-07    1.265283
Freq: D, Name: A, dtype: float64


In [131]:
# Multiple Specific columns
# you can achieve it by passing a list of thos columns you want to select
print(df1[['A','C','D']]) # like this, which is a dataframe

                   A         C         D
2024-08-29  0.158294  0.962826  0.779027
2024-08-30  0.571415  0.166042 -0.584373
2024-08-31  0.157738 -0.337934  1.557236
2024-09-01 -1.968210 -0.642852  0.011324
2024-09-02  0.658876 -2.520846 -0.901576
2024-09-03  0.714369  0.431147 -1.430411
2024-09-04 -0.354987 -1.002914  0.440027
2024-09-05 -2.192925  1.371032  0.138926
2024-09-06 -0.206288 -1.651362 -0.084739
2024-09-07  1.265283  0.875576 -0.502698


### Slicing Based on Row Number

In [153]:
print(df1[:4]) # row splicing works like array
# since rows are originaly an index
# but

                   A         B         C         D
2024-08-29  0.158294 -0.152097  0.962826  0.779027
2024-08-30  0.571415 -0.791438  0.166042 -0.584373
2024-08-31  0.157738  0.248846 -0.337934  1.557236
2024-09-01 -1.968210 -0.833159 -0.642852  0.011324


In [154]:
print(df1.iloc[[2,4]]) # but for multiple specific rows, use iloc
# doing df1[[0,4]] is criminally mortal sin (gives an error everybody)
# just pass a list of your specific rows

                   A         B         C         D
2024-08-31  0.157738  0.248846 -0.337934  1.557236
2024-09-02  0.658876 -1.296092 -2.520846 -0.901576


In [155]:
# also for single specifics, use iloc
print(df1.iloc[1])

A    0.571415
B   -0.791438
C    0.166042
D   -0.584373
Name: 2024-08-30 00:00:00, dtype: float64


### Slicing Based on Row and Column Numbers

In [167]:
# but sometimes you don't want to be specific in just rows, or just columns so
print(df1.iloc[[1,2],[1,2]]) # You use iloc
# .iloc[[rows],[columns]]

                   B         C
2024-08-30 -0.791438  0.166042
2024-08-31  0.248846 -0.337934


In [158]:
print(df1.iloc[[1],[-1]]) # same as this

                   D
2024-08-30 -0.584373


### Slicing Based on Labels

In [162]:
# if you want to base it to labels in your data frame (like column names or your custom indexing)
# use loc!
print(df1.loc["20240830":"20240904"]) # row indexing is a datetimindex type

                   A         B         C         D
2024-08-30  0.571415 -0.791438  0.166042 -0.584373
2024-08-31  0.157738  0.248846 -0.337934  1.557236
2024-09-01 -1.968210 -0.833159 -0.642852  0.011324
2024-09-02  0.658876 -1.296092 -2.520846 -0.901576
2024-09-03  0.714369 -0.144770  0.431147 -1.430411
2024-09-04 -0.354987 -1.719900 -1.002914  0.440027


In [170]:
print(df1.loc[["20240830":"20240904"],"A":"C"]) # but you can use "start:end" concept
# you can't do that in iloc
# arrays have "start:stop"

                   A         B         C
2024-08-30  0.571415 -0.791438  0.166042
2024-09-04 -0.354987 -1.719900 -1.002914


In [171]:
print(df1.loc[["20240830","20240904"],["A","C"]]) # and for super specifics, pass a list

                   A         C
2024-08-30  0.571415  0.166042
2024-09-04 -0.354987 -1.002914


In [174]:
print(df1.loc["20240830",["A","D"]]) # go crazy and experiment
# just remember .loc[[row],[col]]

A    0.571415
D   -0.584373
Name: 2024-08-30 00:00:00, dtype: float64


### Selecting a Single Cell in a DataFrame